language: node_js
node_js:
  - "10.6.0"
services:
  - redis-server
install:
  - yarn install
script:
  - yarn run lint
  - yarn run coverage
after_script:
  - yarn global add codecov
  - yarn run report-coverage
